export const promptMessage = {
    chatMissing: 'Execute `ict new <chatName>` first.',
    onlyOneChat: 'There is currently only one chat.',
    settingMissing: 'Execute `ist cf -m` first to configure LLMSetting.',
    providerMissing: 'At least one provider must be selected.',
    modelMissing: 'At least one model must be selected.',
    systemPromptNoMatching: 'No matching system prompt found.',
    systemPromptMissing: 'The system prompt has not been configured.',
    assistantMissing: 'Assistant Content Missing.',
    hisMsgMissing: 'No message history found.',
    oneChatRemain: 'At least one chat must remain.',
    noEdit: 'No modifications.',
    presetMsgMissing: 'No preset message is configured.',
    cfParseErr: 'Configuration parsing error.',
    mcpMissing: 'No MCP Servers are configured or enabled.',
    userPreset: '<user message content>',
    assistantPreset: '<assistant message content>',
    onlyOneTopic: 'There is currently only one topic.',
    topicMissing: 'No topics are available.',
    topicIdMissing: 'No Topic is Selected.',
    retryOptionsMisssing: 'No recent question.',
}
